# Generated by Django 4.2.1 on 2023-10-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cli', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.CharField(max_length=10)),
                ('nombre_emp', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=10)),
                ('salario', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehi', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=6)),
                ('modelo', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=10)),
                ('año', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=6)),
                ('nombre_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('producto', models.CharField(max_length=20)),
                ('nombre_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('nombre_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nombre_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('rut_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo'),
        ),
    ]
